### ISSUE TITLE
Add -t && --token-usage support to display token information

### ISSUE THREAD

**Issue by mulla028** [theoforger/mastermind#11]
## Description
* Create a new feature to support -t & --token-usage to display token information
* Update README.md file 
* Update main file

## Tasks checklist

- [x] Create a support of -t & --token-usage to display token information using stderr 
- [x] Provide feature in main file
- [x] Update README.md file

**Comment by theoforger** [comment]
Fixed with #12
