### ISSUE TITLE
[Feature] Multiple language models at once

### ISSUE THREAD

**Issue by theoforger** [theoforger/mastermind#16]
### Description
Currently, the project only handles one output, therefore only allows one language model option. This issue requests support for multiple language models. The output should be an aggregated table of clues and their respective sources

### Tasks

- [x] Add Source field to the `Clue` module
- [x] Add Source field to the output
- [x] Handle API calls to multiple models
- [x] Handle multiple inputs after the `-m` option

### Expected Result
Run:
```bash
mastermind link.txt avoid.txt -m gemma2-9b-it mixtral-8x7b-32768
```
Output:
```bash
╭───────┬───────┬───────────────────────────────────┬────────────────────╮
│  Clue ┆ Count ┆       Linked Words                ┆       Source       │
╞═══════╪═══════╪═══════════════════════════════════╪════════════════════╡
│ bond  ┆   5   ┆ sound, penny, bee, walrus, tokyo  ┆ mixtral-8x7b-32768 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ sound ┆   4   ┆ bond, bee, park, tokyo            ┆ mixtral-8x7b-32768 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ park  ┆   3   ┆ scuba, walrus, hospital           ┆ gemma2-9b-it       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ bond  ┆   3   ┆ bee, tokyo, penny                 ┆ gemma2-9b-it       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ sound ┆   2   ┆ bee, walrus                       ┆ gemma2-9b-it       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ large ┆   2   ┆ walrus, tokyo                     ┆ mixtral-8x7b-32768 │
╰───────┴───────┴───────────────────────────────────┴────────────────────╯
```

**Comment by theoforger** [comment]
Implemented by commit d6d8bfcc2a4e0116122fff0eca83a5412f5b1496
